apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:controller:xqueuejob-controller
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
rules:
  - apiGroups:
      - mcad.ibm.com
    resources:
      - xqueuejobs
      - queuejobs
      - schedulingspecs
      - appwrappers
      - appwrappers/finalizers
      - appwrappers/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
      - namespaces
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  #{{ if .Values.quotaManagement.rbac.apiGroup }}
  #{{ if .Values.quotaManagement.rbac.resource }}
  - apiGroups:
      - {{ .Values.quotaManagement.rbac.apiGroup }}
    resources:
      - {{ .Values.quotaManagement.rbac.resource }}
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  #{{ end }}
  #{{ end }}
  #{{ if .Values.coscheduler.rbac.apiGroup }}
  #{{ if .Values.coscheduler.rbac.resource }}
  - apiGroups:
      - {{ .Values.coscheduler.rbac.apiGroup }}
    resources:
      - {{ .Values.coscheduler.rbac.resource }}
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
#{{ end }}
#{{ end }}