kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcad-controller-{{.Name}}
  namespace: {{.Namespace}}
  labels:
    app: mcad-{{.Name}}
    component: multi-cluster-application-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcad-{{.Name}}
  template:
    metadata:
      labels:
        app: mcad-{{.Name}}
        component: multi-cluster-application-dispatcher
    spec:
      containers:
        - name: mcad-controller
        -  # {{ if (eq .Values.configMap.multiCluster true) }}
          args: ["--v", "10", "--logtostderr", "--secure-port=6443"]
          # {{ end }}
          # {{ if (eq .Values.configMap.multiCluster false) }}
#          args: [ "--v", "{{ .Values.loglevel }}", "--logtostderr" ]
          # {{ end }}
          command:
            - mcad-controller
          # {{ if .Values.configMap.name }}
          envFrom:
            - configMapRef:
                name: mcad-controller-configmap
          image: {{.APIServerImage}}
          imagePullPolicy: Always
          ports:
            - name: https
              containerPort: 6443
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          # Also dynamic based on helm chart
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '2'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: temp-vol
              mountPath: /tmp
            # {{ if .Values.volumes.hostPath }}
            - name: agent-config-vol
              mountPath: /root/kubernetes
        # {{ if .Values.configMap.quotaRestUrl }}
        - name: "quota-httpserver"
          image: "{{ .Values.httpServerImage.repository }}:{{ .Values.httpServerImage.tag }}"
          imagePullPolicy: {{.Values.httpServerImage.pullPolicy}}
          ports:
            - containerPort: 80
        - name: "quota-management"
          image: "{{ .Values.httpImage.repository }}:{{ .Values.httpImage.tag }}"
          imagePullPolicy: {{.Values.httpImage.pullPolicy}}
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /tmp
              name: temp-vol
            # {{ if .Values.volumes.hostPath }}
            - name: agent-config-vol
              mountPath: /root/kubernetes
        # {{ end }}
        # {{ end }}
      nodeSelector:
        kubernetes.io/hostname: {{.Values.nodeSelector.hostname}}
      serviceAccountName: mcad-controller-{{.Name}}
      volumes:
        - name: temp-vol
          emptyDir: {}
        # {{ if .Values.volumes.hostPath }}
        - name: agent-config-vol
          hostPath:
            path: {{.Values.volumes.hostPath}}
