apiVersion: v1
kind: Service
metadata:
  name: mcad-{{.Name}}-metrics
  namespace: {{.Namespace}}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: mcad-{{.Name}}
