extends: default
rules:
  line-length: disable
  document-start: disable
  indentation:
    indent-sequences: whatever
  comments-indentation: disable
  hyphens:
    max-spaces-after: 4
  truthy:
    check-keys: false

