---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workload-codeflare-dev-v1beta2-appwrapper
  failurePolicy: Fail
  name: mappwrapper.kb.io
  rules:
  - apiGroups:
    - workload.codeflare.dev
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    resources:
    - appwrappers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-workload-codeflare-dev-v1beta2-appwrapper
  failurePolicy: Fail
  name: vappwrapper.kb.io
  rules:
  - apiGroups:
    - workload.codeflare.dev
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - appwrappers
  sideEffects: None
