apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: openshift-operators
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: codeflare-operator-raycluster-webhook-cert
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/part-of: codeflare
    app.kubernetes.io/name: codeflare-operator
