package controllers

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	MCADImage       = "quay.io/project-codeflare/mcad-controller:dev"
	InstaScaleImage = "quay.io/project-codeflare/instascale-controller:dev"
)
