package controllers

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	MCADImage       = "quay.io/project-codeflare/mcad-controller:release-v1.32.0"
	InstaScaleImage = "quay.io/project-codeflare/instascale-controller:v0.0.5"
)
