apiVersion: v1
kind: Service
metadata:
  name: manager-metrics
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: codeflare-operator
    app.kubernetes.io/part-of: codeflare
