# permissions for end users to view mcads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcad-viewer-role
rules:
- apiGroups:
  - codeflare.codeflare.dev
  resources:
  - mcads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - codeflare.codeflare.dev
  resources:
  - mcads/status
  verbs:
  - get
