# permissions for end users to edit mcads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcad-editor-role
rules:
- apiGroups:
  - codeflare.codeflare.dev
  resources:
  - mcads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - codeflare.codeflare.dev
  resources:
  - mcads/status
  verbs:
  - get
