package support

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	CodeFlareSDKVersion = "0.10.0"
	RayVersion          = "2.5.0"
	RayImage            = "rayproject/ray:2.5.0"
)
