/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// InstaScaleSpecApplyConfiguration represents an declarative configuration of the InstaScaleSpec type for use
// with apply.
type InstaScaleSpecApplyConfiguration struct {
	EnableMonitoring    *bool                    `json:"enableMonitoring,omitempty"`
	MaxScaleoutAllowed  *int                     `json:"maxScaleoutAllowed,omitempty"`
	UseMachinePools     *bool                    `json:"useMachinePools,omitempty"`
	ControllerResources *v1.ResourceRequirements `json:"controllerResources,omitempty"`
	ControllerImage     *string                  `json:"controllerImage,omitempty"`
}

// InstaScaleSpecApplyConfiguration constructs an declarative configuration of the InstaScaleSpec type for use with
// apply.
func InstaScaleSpec() *InstaScaleSpecApplyConfiguration {
	return &InstaScaleSpecApplyConfiguration{}
}

// WithEnableMonitoring sets the EnableMonitoring field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableMonitoring field is set to the value of the last call.
func (b *InstaScaleSpecApplyConfiguration) WithEnableMonitoring(value bool) *InstaScaleSpecApplyConfiguration {
	b.EnableMonitoring = &value
	return b
}

// WithMaxScaleoutAllowed sets the MaxScaleoutAllowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxScaleoutAllowed field is set to the value of the last call.
func (b *InstaScaleSpecApplyConfiguration) WithMaxScaleoutAllowed(value int) *InstaScaleSpecApplyConfiguration {
	b.MaxScaleoutAllowed = &value
	return b
}

// WithUseMachinePools sets the UseMachinePools field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseMachinePools field is set to the value of the last call.
func (b *InstaScaleSpecApplyConfiguration) WithUseMachinePools(value bool) *InstaScaleSpecApplyConfiguration {
	b.UseMachinePools = &value
	return b
}

// WithControllerResources sets the ControllerResources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerResources field is set to the value of the last call.
func (b *InstaScaleSpecApplyConfiguration) WithControllerResources(value v1.ResourceRequirements) *InstaScaleSpecApplyConfiguration {
	b.ControllerResources = &value
	return b
}

// WithControllerImage sets the ControllerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerImage field is set to the value of the last call.
func (b *InstaScaleSpecApplyConfiguration) WithControllerImage(value string) *InstaScaleSpecApplyConfiguration {
	b.ControllerImage = &value
	return b
}
