apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeflare-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: codeflare-operator
  source: codeflare-olm-test
  sourceNamespace: olm
  config:
    resources:
      limits:
        cpu: 400m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
