# This workflow will build the MNIST job test image and push it to the project-codeflare image registry

name: MNIST Job Test Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'test/pytorch_mnist_image/**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Go
      uses: actions/setup-go@v3
      with:
        go-version: v1.20

    - name: Login to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_TOKEN }}
        registry: quay.io

    - name: Image Build and Push
      run: |
        make image-mnist-job-test-push
